title: "Pedro Cotovio"
author: "Pedro Giesteira Cotovio"
description: "PhD candidate working on neuro-symbolic AI for ontology matching and knowledge graph alignment."
url: "https://pedrocotovio.github.io"
baseurl: "./"
 
markdown: kramdown
#ins_logo: "./bits-logo.png"
 
 
favicon: true
favicon_location: favicon.ico
 
footer: true
footer_url: "https://github.com/PedroCotovio"
footer_text: ""
 
sass:
    style: compressed
    sass_dir: _sass
 
nav:
 - name: "About"
   link: "./"
 - name: "CV"
   link: "./cv.pdf"
